{
	"version": 1733035321,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/backgorundmainscreen-sheet0.png",
		"images/bghakureisrine-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/fairy-sheet0.png",
		"images/fairy-sheet1.png",
		"images/marisapixel-sheet0.png",
		"images/cloud-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/bullet-sheet0.png",
		"images/facingpoint-sheet0.png",
		"images/pembatas-sheet0.png",
		"images/map-sheet0.png",
		"images/marisaup-sheet0.png",
		"images/marisaup-sheet1.png",
		"images/meilingpixel-sheet0.png",
		"images/red-sheet0.png",
		"images/blue-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/9patch.png",
		"images/playbtn-sheet0.png",
		"images/marisa-sheet0.png",
		"images/marisa-sheet1.png",
		"images/marisa-sheet2.png",
		"images/marisa-sheet3.png",
		"images/marisa-sheet4.png",
		"images/marisa-sheet5.png",
		"images/marisa-sheet6.png",
		"images/judul-sheet0.png",
		"images/ran-sheet0.png",
		"images/ran-sheet1.png",
		"images/ran-sheet2.png",
		"images/ran-sheet3.png",
		"images/ran-sheet4.png",
		"images/ran-sheet5.png",
		"images/ran-sheet6.png",
		"images/ran-sheet7.png",
		"images/ran-sheet8.png",
		"images/ran-sheet9.png",
		"images/collision-sheet0.png",
		"images/mobiletouhoulostwordhakureishrinenight-sheet0.png",
		"images/mobiletouhoulostwordthesky-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/meiling-sheet0.png",
		"images/meiling-sheet1.png",
		"images/meiling-sheet2.png",
		"images/sprite9-sheet0.png",
		"images/sprite9-sheet1.png",
		"images/sprite9-sheet2.png",
		"images/bumpy_skyblue_021024x-sheet0.png",
		"images/sprite6-sheet0.png",
		"media/audio-editor-output.ogg",
		"media/swords collide - sound effect [tuberipper.cc].ogg",
		"media/y2mate.com-in-stage-4-powerful-boss-marisa-kirisames-theme-lovecolored-master-spark.ogg",
		"media/a porch in sunbeams filtered through trees (main menu) - touhou lost word music extended [tuberipper.cc].ogg",
		"media/eosd stage 2 boss - cirnos theme - beloved tomboyish girl [tuberipper.cc].ogg",
		"media/akaishimaicake to kashikoimont blanc (scarlet devil tower) - touhou lost word music extended [tuberipper.cc].ogg",
		"media/touhou - shanghai alice of meiji 17 metal cover by richaadeb [tuberipper.cc].ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}